CREATE SEQUENCE seq_cidade;

CREATE TABLE CIDADE(
id INTEGER NOT NULL,
nome CHARACTER VARYING NOT NULL,
estado CHARACTER VARYING NOT NULL,
CONSTRAINT cidade_pkey PRIMARY KEY (id)
);

CREATE SEQUENCE seq_cliente;

CREATE TABLE CLIENTE(
id INTEGER NOT NULL,
nomecompleto CHARACTER VARYING NOT NULL,
sexo INTEGER NOT NULL,
datanascimento DATE NOT NULL,
idade INTEGER NOT NULL,
cidade_id INTEGER NOT NULL,
CONSTRAINT cliente_pkey PRIMARY KEY (id),
CONSTRAINT fk_cliente_cidade FOREIGN KEY (cidade_id) REFERENCES cidade (id)
);